def die(error):
    print('O programa teve o seguinte erro: |', error, '| e inesperadamente precisou ser encerrado.')
    exit(1)